apiVersion: v1

kind: ReplicationController

metadata:

  name: selenium-node-firefox-rep

spec:

  replicas: 3

  selector:

    app: selenium-node-firefox

  template:

    metadata:

      name: wedriverio-node-firefox

      labels:

        app: wedriverio-node-firefox

    spec:

      containers:

        - name: wedriverio-node-firefox

          image: mydemo/node-firefox      #image from docker build

          ports:

            - containerPort: 5901

          env:

            - name:  HUB_HOST

              value: "wedriverio-srv"

            - name: HUB_PORT

              value: "4444"